[package]
name = "leaderboard-app"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.143"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tui-input = "0.14.0"
tui-textarea = "0.7.0"
